version: "3"
services:

  api01: &api
    image: victoremerick/magis5:latest
    build:
      context: ../
      dockerfile: ./devops/Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=jdbc:mysql://mysql:5432/estoque_bebidas
      - DB_USER=root
      - DB_PASSWORD=root_password
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
      # Essa sintaxe reusa o que foi declarado em 'api01'.
      <<: *api
      hostname: api02
      environment:
        - DB_HOSTNAME=jdbc:mysql://mysql:5432/estoque_bebidas
        - DB_USER=root
        - DB_PASSWORD=root_password
      ports:
        - "8082:8080"
      depends_on:
        - mysql
      deploy:
        resources:
          limits:
            cpus: "0.6"
            memory: "200MB"

  nginx:
      hostname: nginx
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api01
        - api02
      ports:
        - "9999:9999"
      deploy:
        resources:
          limits:
            cpus: "0.17"
            memory: "10MB"

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: estoque_bebidas
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
