spring:
  application:
    name: magis5-teste
  datasource:
    url: ${DB_HOSTNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: false
logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs:
    path: /doc/api-docs
  swagger-ui:
    path: /doc/documentation.html

